version: '3'

services:
    neurofood:
        build: .
        restart: unless-stopped
        volumes:
            - "./:/opt/app/"
        environment:
            CONTAINER_FLASK_PORT: ${FLASK_PORT:-80}
            EXTERNAL_FLASK_PORT: ${FLASK_PORT:-8087}
        ports:
          - ${EXTERNAL_FLASK_PORT:-8087}:80