version: '3'

services:
    neurofood:
        build: .
        restart: unless-stopped
        volumes:
            - "./:/opt/app"
        environment:
            CONTAINER_FLASK_PORT: ${CONTAINER_FLASK_PORT:-80}
            EXTERNAL_FLASK_PORT: ${EXTERNAL_FLASK_PORT:-8087}
            FLASK_DEBUG: ${FLASK_DEBUG:-true}
        ports:
          - ${EXTERNAL_FLASK_PORT:-8087}:80