version: '3.2'

services:
    neurofood:
        build: .
        restart: unless-stopped
        volumes:
            - "./neuro:/opt/app/neuro"
            - "./data:/opt/app/data"
            - "./web:/opt/app/web"
            - "./app.py:/opt/app/app.py"
            - "./config.py:/opt/app/config.py"
            - "./crontab:/opt/app/crontab"
        environment:
            CONTAINER_FLASK_PORT: ${CONTAINER_FLASK_PORT:-5000}
            EXTERNAL_FLASK_PORT: ${EXTERNAL_FLASK_PORT:-8080}
            FLASK_DEBUG: ${FLASK_DEBUG:-true}
            DEV_MODE: ${DEV_MODE:-true}
            ALPHA: ${ALPHA:-4}
            NUM_ITERS: ${NUM_ITERS:-200}
            LAMBDA_PARAM: ${LAMBDA_PARAM:-0.5}
        ports:
          - 80:80